ZSH_THEME="avit"

plugins=(
    zsh-syntax-highlighting
    zsh-autosuggestions
    zsh-completions
)

export PATH=~/.composer/vendor/bin:/usr/local/opt/binutils/bin:/usr/local/go/bin:/usr/local/sbin:$PATH
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8

# For tmux auto-suggestions highlight problems
export TERM=xterm-256color

# Golang
export GOPATH=$(go env GOPATH)
export PATH=$GOPATH/bin:$PATH

# Default Editor
export EDITOR=vim

alias loadnvm=". /usr/local/opt/nvm/nvm.sh"
alias ipy="ipython3"
alias youtube-mp3="youtube-dl -x --audio-format mp3"
alias tmp="cd /tmp"
