ZSH_THEME="avit"

plugins=(
    git
    zsh-syntax-highlighting
    zsh-autosuggestions
    zsh-completions
)

export PATH=~/.composer/vendor/bin:/usr/local/opt/binutils/bin:$PATH
export ZSH=$HOME/.oh-my-zsh

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8
export TERM=xterm-256color # For tmux auto-suggestions highlight problems

# Golang
export GOPATH=$(go env GOPATH)

alias loadnvm=". /usr/local/opt/nvm/nvm.sh"
alias pip="pip3"
alias ipy="ipython3"
